model_type = "auto_regressive"

num_cells = 32
vocab_size = 65536
embedded_dim = 4096
num_heads = 64
channel_mix_dim_scale = 4
dropout_prob = 0.01

with_token_shift = true
with_deep_embed_att = false
with_deep_embed_ffn = false
