http_bind_addr = "0.0.0.0:8080"
request_body_limit_bytes = 52428800
sse_keep_alive_ms = 10000

[[models]]
model_name = "rwkv-lm-7.2b"
model_cfg = "rwkv-lm-7.2b"
weights_path = "../../weights/rwkv7-g1d-7.2b-20260131-ctx8192.mpk"
tokenizer_vocab_path = "../../assets/rwkv_vocab_v20230424.txt"
device_type = 0
device_ids = [0]
max_batch_size = 4
max_context_len = 4096
paragraph_len = 256
decode_first = true
